title: He Wei
description: My Personal Blog
author: John Smith
github: https://github.com/HW-hideonbush
about: 

baseurl: "https://hw-hideonbush.github.io/"
url: "https://hw-hideonbush.github.io/"

allowsearch: true

disqus_shortname: aboutashu

enableTags: true
tagarray: []

paginate: 20
per_page: 20
paginate_path: "/page:num/"
markdown: kramdown
gems: [jekyll-paginate, jekyll-gist]
